# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

services:
  "gitlab.admin.ehealth.sundhed.dk": "gitlab:gitlab.admin.ehealth.sundhed.dk"

git:
  parseEmoji: true

gui:
  nerdFontsVersion: "3"

  # https://github.com/catppuccin/lazygit/blob/main/themes/mocha/blue.yml
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

customCommands:
  # https://gist.github.com/timhagel/28ae03354a85ce3e5237b308912b9b52
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"'
    description: "conventional commit"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat"
          - name: "Fix"
            description: "a bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Styling changes (white-space, formatting, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "Refactoring code"
            value: "refactor"
          - name: "Performance Improvements"
            description: "Performance improvements"
            value: "perf"
          - name: "Tests"
            description: "Test additions or fixes"
            value: "test"
          - name: "Builds"
            description: "Build system or dependency changes"
            value: "build"
          - name: "Continuous Integration"
            description: "CI configuration changes"
            value: "ci"
          - name: "Chores"
            description: "Other non-code changes"
            value: "chore"
          - name: "Reverts"
            description: "Reverting changes"
            value: "revert"
      - type: "menu"
        title: "Choose the emoji for this commit type."
        key: "Emoji"
        options:
          - name: "ğŸ¨ Improve structure / format of the code."
            value: ":art:"
          - name: "âš¡ï¸ Improve performance."
            value: ":zap:"
          - name: "ğŸ”¥ Remove code or files."
            value: ":fire:"
          - name: "ğŸ› Fix a bug."
            value: ":bug:"
          - name: "ğŸš‘ï¸ Critical hotfix."
            value: ":ambulance:"
          - name: "âœ¨ Introduce new features."
            value: ":sparkles:"
          - name: "ğŸ“ Add or update documentation."
            value: ":memo:"
          - name: "ğŸš€ Deploy stuff."
            value: ":rocket:"
          - name: "ğŸ’„ Add or update the UI and style files."
            value: ":lipstick:"
          - name: "ğŸ‰ Begin a project."
            value: ":tada:"
          - name: "âœ… Add, update, or pass tests."
            value: ":white_check_mark:"
          - name: "ğŸ”’ï¸ Fix security or privacy issues."
            value: ":lock:"
          - name: "ğŸ” Add or update secrets."
            value: ":closed_lock_with_key:"
          - name: "ğŸ”– Release / Version tags."
            value: ":bookmark:"
          - name: "ğŸš¨ Fix compiler / linter warnings."
            value: ":rotating_light:"
          - name: "ğŸš§ Work in progress."
            value: ":construction:"
          - name: "ğŸ’š Fix CI Build."
            value: ":green_heart:"
          - name: "â¬‡ï¸ Downgrade dependencies."
            value: ":arrow_down:"
          - name: "â¬†ï¸ Upgrade dependencies."
            value: ":arrow_up:"
          - name: "ğŸ“Œ Pin dependencies to specific versions."
            value: ":pushpin:"
          - name: "ğŸ‘· Add or update CI build system."
            value: ":construction_worker:"
          - name: "ğŸ“ˆ Add or update analytics or track code."
            value: ":chart_with_upwards_trend:"
          - name: "â™»ï¸ Refactor code."
            value: ":recycle:"
          - name: "â• Add a dependency."
            value: ":heavy_plus_sign:"
          - name: "â– Remove a dependency."
            value: ":heavy_minus_sign:"
          - name: "ğŸ”§ Add or update configuration files."
            value: ":wrench:"
          - name: "ğŸ”¨ Add or update development scripts."
            value: ":hammer:"
          - name: "ğŸŒ Internationalization and localization."
            value: ":globe_with_meridians:"
          - name: "âœï¸ Fix typos."
            value: ":pencil2:"
          - name: "ğŸ’© Write bad code that needs to be improved."
            value: ":poop:"
          - name: "âªï¸ Revert changes."
            value: ":rewind:"
          - name: "ğŸ”€ Merge branches."
            value: ":twisted_rightwards_arrows:"
          - name: "ğŸ“¦ï¸ Add or update compiled files or packages."
            value: ":package:"
          - name: "ğŸ‘½ï¸ Update code due to external API changes."
            value: ":alien:"
          - name: "ğŸšš Move or rename resources (e.g.: files, paths, routes)."
            value: ":truck:"
          - name: "ğŸ“„ Add or update license."
            value: ":page_facing_up:"
          - name: "ğŸ’¥ Introduce breaking changes."
            value: ":boom:"
          - name: "ğŸ± Add or update assets."
            value: ":bento:"
          - name: "â™¿ï¸ Improve accessibility."
            value: ":wheelchair:"
          - name: "ğŸ’¡ Add or update comments in source code."
            value: ":bulb:"
          - name: "ğŸ» Write code drunkenly."
            value: ":beers:"
          - name: "ğŸ’¬ Add or update text and literals."
            value: ":speech_balloon:"
          - name: "ğŸ—ƒï¸ Perform database related changes."
            value: ":card_file_box:"
          - name: "ğŸ”Š Add or update logs."
            value: ":loud_sound:"
          - name: "ğŸ”‡ Remove logs."
            value: ":mute:"
          - name: "ğŸ‘¥ Add or update contributor(s)."
            value: ":busts_in_silhouette:"
          - name: "ğŸš¸ Improve user experience / usability."
            value: ":children_crossing:"
          - name: "ğŸ—ï¸ Make architectural changes."
            value: ":building_construction:"
          - name: "ğŸ“± Work on responsive design."
            value: ":iphone:"
          - name: "ğŸ¤¡ Mock things."
            value: ":clown_face:"
          - name: "ğŸ¥š Add or update an easter egg."
            value: ":egg:"
          - name: "ğŸ™ˆ Add or update a .gitignore file."
            value: ":see_no_evil:"
          - name: "ğŸ“¸ Add or update snapshots."
            value: ":camera_flash:"
          - name: "âš—ï¸ Perform experiments."
            value: ":alembic:"
          - name: "ğŸ”ï¸ Improve SEO."
            value: ":mag:"
          - name: "ğŸ·ï¸ Add or update types."
            value: ":label:"
          - name: "ğŸŒ± Add or update seed files."
            value: ":seedling:"
          - name: "ğŸš© Add, update, or remove feature flags."
            value: ":triangular_flag_on_post:"
          - name: "ğŸ¥… Catch errors."
            value: ":goal_net:"
          - name: "ğŸ’« Add or update animations and transitions."
            value: ":dizzy:"
          - name: "ğŸ—‘ï¸ Deprecate code that needs to be cleaned up."
            value: ":wastebasket:"
          - name: "ğŸ›‚ Work on code related to authorization, roles and permissions."
            value: ":passport_control:"
          - name: "ğŸ©¹ Simple fix for a non-critical issue."
            value: ":adhesive_bandage:"
          - name: "ğŸ§ Data exploration/inspection."
            value: ":monocle_face:"
          - name: "âš°ï¸ Remove dead code."
            value: ":coffin:"
          - name: "ğŸ§ª Add a failing test."
            value: ":test_tube:"
          - name: "ğŸ‘” Add or update business logic."
            value: ":necktie:"
          - name: "ğŸ©º Add or update healthcheck."
            value: ":stethoscope:"
          - name: "ğŸ§± Infrastructure related changes."
            value: ":bricks:"
      - type: "input"
        title: "Enter optional scope of the change."
        key: "Scope"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"
